### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project3#101]
I've been getting the following issue when I'm trying to deploy:

```
2015-12-10T15:03:34.428653+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-ridge-6206.herokuapp.com request_id=eea43a10-2fc0-4980-9f23-3540a5035b52 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T15:03:33.252446+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secure-ridge-6206.herokuapp.com request_id=34cf2e02-6fed-4815-b02e-23af24c95131 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
```

The favicon.ico file appears to be referring to middleware in the modules, but I can't figure out any more than that.

**Comment by RobertAKARobin** [comment]
The favicon's not causing the problem. That error gets ignored. I'd recommend trying out some of the things in here:

https://devcenter.heroku.com/articles/troubleshooting-node-deploys

My guess is that it's most likely a Mongoose thing. Does `heroku run node db/seeds.js` work?

**Comment by jshawl** [comment]
what is the output of `heroku logs`?

**Comment by rebeccaestes** [comment]
I think it does have to do with Mongoose. `heroku run node db/seeds.js` gets an error. We have that set up to console.log some random locations that are in an array, and then to console.log when they're saved. The first set of console.logs are displaying, but none of the save notifications. The error we're getting when it aborts is:

```
/app/node_modules/mongoose/node_modules/mongodb/lib/server.js:235
        process.nextTick(function() { throw err; })
```

I looked at <a href="https://devcenter.heroku.com/articles/nodejs-mongoose">these</a> <a href="https://devcenter.heroku.com/articles/mongohq">articles<a>, but they wanted me to run, `heroku addons:create mongolab`, which requires a credit card number?? Then I found <a href="https://devcenter.heroku.com/articles/mongolab">this</a> and thought maybe we needed to add PROD_MONGODB to the passwords in the Heroku dashboard, but I don't think that was it. The line in our schema says `var conn = mongoose.connect(process.env.PROD_MONGODB || 'mongodb://127.0.0.1:27017/locations');` and prod_mongodb isn't anywhere else in the app ...

**Comment by jshawl** [comment]
recommend `process.env.MONGOLAB_URI` - https://devcenter.heroku.com/articles/mongolab#adding-mongolab-as-a-heroku-add-on

**Comment by RobertAKARobin** [comment]
No CC needed. Go to mongolab.com, sign up, and pick the "Single-Node, Standard Line" package.

**Comment by RobertAKARobin** [comment]
@jshawl Does the name of the environment variable make a difference?

**Comment by jshawl** [comment]
not sure but you can see all your env variables with `heroku config`

**Comment by rebeccaestes** [comment]
I added the MONGOLAB_URI config variable on my dashboard, but I don't have it anywhere in my actual app. So obviously nothing is changing. Where is it supposed to be?

**Comment by jshawl** [comment]
on heroku! what is the output of `heroku config`

**Comment by rebeccaestes** [comment]
It lists 4 yelp API keys, one passport key, and MONGOLAB_URI.

**Comment by jshawl** [comment]
ok great! problem solved?

**Comment by rebeccaestes** [comment]
No :disappointed:. Different error:

```
2015-12-10T16:07:53.132408+00:00 app[web.1]: Error: Trying to open unclosed connection.
```

**Comment by jshawl** [comment]
can you share more of the error?

**Comment by rebeccaestes** [comment]
The error changes depending on whether or not we comment out this line in app.js:

`// mongoose.connect('mongodb://localhost/local-authentication-with-passport');
`

When we don't comment it out, we get the unclosed connection error above. When we do:

```
2015-12-10T16:09:49.447795+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-12-10T16:09:49.540914+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-10T16:09:49.370842+00:00 app[web.1]: The Prancing Pirate is a Irish bar with score 7
2015-12-10T16:09:49.540948+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2015-12-10T16:09:49.540889+00:00 app[web.1]: 
2015-12-10T16:09:49.540912+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mongodb/lib/server.js:235
2015-12-10T16:09:49.540960+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-10T16:09:49.540949+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2015-12-10T16:09:50.422224+00:00 heroku[web.1]: Process exited with status 1
2015-12-10T16:09:50.438805+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-10T16:09:53.031459+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-ridge-6206.herokuapp.com request_id=82f7b30f-4044-449d-8a9a-99775328a1eb fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:09:51.757133+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secure-ridge-6206.herokuapp.com request_id=3bc3a2d1-99d9-487b-93fc-a81ead855983 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
```

**Comment by jshawl** [comment]
instead, use:

``` js
mongoose.connect(process.env.MONGOLAB_URI || 'mongodb://localhost/local-authentication-with-passport')
```

**Comment by rebeccaestes** [comment]
`Error: Trying to open unclosed connection.` returns.

When we do `heroku run node app.js` it gives more details:

```
Error: Trying to open unclosed connection.
    at NativeConnection.Connection.open (/app/node_modules/mongoose/lib/connection.js:226:15)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:229:15)
    at Object.<anonymous> (/app/app.js:16:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by jshawl** [comment]
can you link to your code?

**Comment by rebeccaestes** [comment]
https://github.com/MarkhamShofner/Project-3-API/tree/heroku_deployment

**Comment by jshawl** [comment]
can you paste the whole output of heroku logs again?

**Comment by rebeccaestes** [comment]
'The Stinky Knight' etc. are our seeds console.logging that they've been created.  They should also be console logging that they've been saved, but that's not working.

```
2015-12-10T16:18:56.077062+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-ridge-6206.herokuapp.com request_id=c98d1f36-669b-43d4-9fc5-f536fca804a1 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:18:54.900445+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secure-ridge-6206.herokuapp.com request_id=e5e6b313-6e71-4624-a6dd-afb32215ba5d fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:22:59.326952+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-10T16:22:59.326933+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-10T16:22:59.254622+00:00 heroku[api]: Deploy 1e326b3 by estes.rebecca@gmail.com
2015-12-10T16:22:59.254622+00:00 heroku[api]: Release v47 created by estes.rebecca@gmail.com
2015-12-10T16:23:04.630526+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-ridge-6206.herokuapp.com request_id=f237d354-e9da-4fba-b036-98cf6e4e166f fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:23:03.339828+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secure-ridge-6206.herokuapp.com request_id=d72aaeb6-dd97-4c22-a85d-2ee0987f9797 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:23:04.629423+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-ridge-6206.herokuapp.com request_id=79551879-3d21-4d97-a542-e7086649df20 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:23:11.226148+00:00 heroku[web.1]: Starting process with command `node app.js`
2015-12-10T16:23:14.570656+00:00 app[web.1]: The Stinky Warthog is a Irish bar with score 7
2015-12-10T16:23:14.642203+00:00 app[web.1]: Thu, 10 Dec 2015 16:23:14 GMT body-parser deprecated undefined extended: provide extended option at node_modules/body-parser/index.js:105:29
2015-12-10T16:23:14.569909+00:00 app[web.1]: The Stinky Knight is a Rave warehouse with score 6
2015-12-10T16:23:14.573079+00:00 app[web.1]: The Frolicking Crab is a Brewery with score 0
2015-12-10T16:23:14.748827+00:00 app[web.1]: 
2015-12-10T16:23:14.748838+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-12-10T16:23:14.748832+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-10T16:23:14.748831+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mongodb/lib/server.js:235
2015-12-10T16:23:14.748834+00:00 app[web.1]:                                       ^
2015-12-10T16:23:14.573333+00:00 app[web.1]: The Stinky Warthog is a Rave warehouse with score 8
2015-12-10T16:23:14.748839+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2015-12-10T16:23:14.748839+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2015-12-10T16:23:14.573600+00:00 app[web.1]: The Happy Crab is a Dive bar with score 2
2015-12-10T16:23:14.748840+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-10T16:23:15.632417+00:00 heroku[web.1]: Process exited with status 1
2015-12-10T16:23:15.628346+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-10T16:23:08.995893+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-10T16:23:14.570370+00:00 app[web.1]: The Drunken Stag is a English pub with score 10
2015-12-10T16:23:14.571640+00:00 app[web.1]: The Drunken Crab is a Nightclub with score 5
2015-12-10T16:23:14.571108+00:00 app[web.1]: The Happy Stag is a Rave warehouse with score 2
2015-12-10T16:23:14.571378+00:00 app[web.1]: The Furious Crab is a Nightclub with score 8
2015-12-10T16:23:14.571910+00:00 app[web.1]: The Smelly Crab is a English pub with score 1
2015-12-10T16:23:14.573926+00:00 app[web.1]: The Frolicking Elephant is a English pub with score 1
2015-12-10T16:23:14.572444+00:00 app[web.1]: The Drunken Stag is a English pub with score 3
2015-12-10T16:23:14.574170+00:00 app[web.1]: The Drunken Warthog is a English pub with score 6
2015-12-10T16:23:14.729121+00:00 app[web.1]: app listening at http://localhost:3000/
2015-12-10T16:23:14.653711+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-12-10T16:23:14.653716+00:00 app[web.1]: designed for a production environment, as it will leak
2015-12-10T16:23:14.653718+00:00 app[web.1]: memory, and will not scale past a single process.
2015-12-10T16:23:14.592071+00:00 app[web.1]: Thu, 10 Dec 2015 16:23:14 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at app.js:20:9
2015-12-10T16:23:14.567394+00:00 app[web.1]: The Drunken Warthog is a English pub with score 1
2015-12-10T16:24:59.025040+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-10T16:24:59.025030+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-10T16:24:58.917098+00:00 heroku[api]: Deploy 06154e4 by estes.rebecca@gmail.com
2015-12-10T16:24:58.917098+00:00 heroku[api]: Release v48 created by estes.rebecca@gmail.com
2015-12-10T16:25:00.582698+00:00 heroku[web.1]: Starting process with command `node app.js`
2015-12-10T16:25:03.806961+00:00 app[web.1]: The Stinky Knight is a Rave warehouse with score 1
2015-12-10T16:25:03.805951+00:00 app[web.1]: The Stinky Stag is a Brewery with score 10
2015-12-10T16:25:03.803170+00:00 app[web.1]: The Frolicking Knight is a Dive bar with score 2
2015-12-10T16:25:03.807338+00:00 app[web.1]: The Frolicking Warthog is a Rave warehouse with score 0
2015-12-10T16:25:03.799122+00:00 app[web.1]: The Furious Stag is a Dive bar with score 5
2015-12-10T16:25:03.803580+00:00 app[web.1]: The Happy Elephant is a Rave warehouse with score 3
2015-12-10T16:25:03.805284+00:00 app[web.1]: The Insolent Crab is a English pub with score 6
2015-12-10T16:25:03.804545+00:00 app[web.1]: The Insolent Stag is a Rave warehouse with score 10
2015-12-10T16:25:03.816568+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2015-12-10T16:25:03.816569+00:00 app[web.1]:       ^
2015-12-10T16:25:03.802365+00:00 app[web.1]: The Smelly Knight is a Brewery with score 3
2015-12-10T16:25:03.816564+00:00 app[web.1]: events.js:141
2015-12-10T16:25:03.806583+00:00 app[web.1]: The Smelly Jester is a Dive bar with score 1
2015-12-10T16:25:03.808072+00:00 app[web.1]: The Insolent Pirate is a Nightclub with score 9
2015-12-10T16:25:03.804149+00:00 app[web.1]: The Smelly Warthog is a Brewery with score 5
2015-12-10T16:25:03.804916+00:00 app[web.1]: The Frolicking Pirate is a Dive bar with score 1
2015-12-10T16:25:03.816575+00:00 app[web.1]:     at NativeConnection.Connection.open (/app/node_modules/mongoose/lib/connection.js:226:15)
2015-12-10T16:25:03.816575+00:00 app[web.1]:     at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:229:15)
2015-12-10T16:25:03.816579+00:00 app[web.1]:     at Function.Module._load (module.js:313:12)
2015-12-10T16:25:03.807714+00:00 app[web.1]: The Drunken Elephant is a Irish bar with score 3
2015-12-10T16:25:03.816574+00:00 app[web.1]: Error: Trying to open unclosed connection.
2015-12-10T16:25:03.816573+00:00 app[web.1]: 
2015-12-10T16:25:03.816577+00:00 app[web.1]:     at Module._compile (module.js:425:26)
2015-12-10T16:25:03.816578+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-12-10T16:25:03.816578+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-10T16:25:03.816580+00:00 app[web.1]:     at startup (node.js:138:18)
2015-12-10T16:25:03.816580+00:00 app[web.1]:     at Function.Module.runMain (module.js:457:10)
2015-12-10T16:25:03.816576+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:16:10)
2015-12-10T16:25:03.816581+00:00 app[web.1]:     at node.js:974:3
2015-12-10T16:25:04.732979+00:00 heroku[web.1]: Process exited with status 1
2015-12-10T16:25:04.748575+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-10T16:27:18.193844+00:00 heroku[api]: Release v49 created by estes.rebecca@gmail.com
2015-12-10T16:27:18.193615+00:00 heroku[api]: Deploy 98f6104 by estes.rebecca@gmail.com
2015-12-10T16:27:18.323465+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-10T16:27:19.891294+00:00 heroku[web.1]: Starting process with command `node app.js`
2015-12-10T16:27:22.648367+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2015-12-10T16:27:22.648401+00:00 app[web.1]:     at NativeConnection.Connection.open (/app/node_modules/mongoose/lib/connection.js:226:15)
2015-12-10T16:27:22.648344+00:00 app[web.1]: events.js:141
2015-12-10T16:27:22.648388+00:00 app[web.1]: 
2015-12-10T16:27:22.648402+00:00 app[web.1]:     at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:229:15)
2015-12-10T16:27:22.648400+00:00 app[web.1]: Error: Trying to open unclosed connection.
2015-12-10T16:27:22.648378+00:00 app[web.1]:       ^
2015-12-10T16:27:22.648403+00:00 app[web.1]:     at Module._compile (module.js:425:26)
2015-12-10T16:27:22.648404+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-10T16:27:22.648405+00:00 app[web.1]:     at Function.Module._load (module.js:313:12)
2015-12-10T16:27:22.648405+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-12-10T16:27:22.648403+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:16:10)
2015-12-10T16:27:22.648406+00:00 app[web.1]:     at Function.Module.runMain (module.js:457:10)
2015-12-10T16:27:22.648407+00:00 app[web.1]:     at startup (node.js:138:18)
2015-12-10T16:27:22.648417+00:00 app[web.1]:     at node.js:974:3
2015-12-10T16:27:18.348796+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-10T16:27:18.348806+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-10T16:27:23.566892+00:00 heroku[web.1]: Process exited with status 1
2015-12-10T16:27:23.580516+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-10T16:27:31.347950+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-ridge-6206.herokuapp.com request_id=b91171ef-f14b-4483-a2fd-e9ef3e923b50 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:27:31.369275+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-ridge-6206.herokuapp.com request_id=d10a6745-0c95-4194-8a60-0175e1a2351d fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:27:30.070321+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secure-ridge-6206.herokuapp.com request_id=6399c856-281c-4eb1-93a0-f3e274f6973c fwd="50.200.196.50" dyno= connect= service= status=503 bytes=

```

**Comment by jshawl** [comment]
https://github.com/MarkhamShofner/Project-3-API/blob/bc18b0920f64673834d225f20a1e191d45e6b0d3/app.js#L16

are you trying to connect more than once?

**Comment by rebeccaestes** [comment]
We do. We have that line in app.js, and a similar one in schema.js ... I commented out app.js and that didn't work, so I'll try schema.

**Comment by rebeccaestes** [comment]
It worked!!!! Mostly - our main feature (a map) is not displaying, but we can log in. I'll close this and start a new issue if we can't get the map up.

**Comment by rebeccaestes** [comment]
'
