### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by schersh** [ga-wdi-exercises/project3#107]
Cassidy and I are working on deploying this morning. Our branch on github is: https://github.com/schersh/Travel_app_project_3/tree/deployment-test
We've followed the heroku tutorial and installed MongoLab, but we are hitting the following error: 

```
2015-12-10T15:26:41.963269+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-10T15:28:45.171604+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=enigmatic-caverns-6880.herokuapp.com request_id=e2326494-21c5-405d-8712-7c461b8cac1d fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T15:28:46.083245+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=enigmatic-caverns-6880.herokuapp.com request_id=c8b7e5a3-27af-45e5-9e19-1df9f28ed0e9 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T15:28:45.560567+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=enigmatic-caverns-6880.herokuapp.com request_id=7b974469-35e6-433d-b2f7-2b44a0f825a2 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T15:52:28.412776+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=enigmatic-caverns-6880.herokuapp.com request_id=c227408a-e7b6-47d8-b0cf-d326d1a3b773 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T15:52:28.792087+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=enigmatic-caverns-6880.herokuapp.com request_id=6970255e-0939-4da3-b942-9016b15ad0f5 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T15:54:41.761224+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=enigmatic-caverns-6880.herokuapp.com request_id=fbd3f959-c221-4a42-baa7-94bf23d5b73c fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T15:54:41.376710+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=enigmatic-caverns-6880.herokuapp.com request_id=0d4adb59-84f0-45bf-8558-80d442152b8c fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T15:54:41.778740+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=enigmatic-caverns-6880.herokuapp.com request_id=b8986a60-0895-4a24-adcb-f3e35c8b509c fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
```

**Comment by jshawl** [comment]
change https://github.com/schersh/Travel_app_project_3/blob/20227c841312eeda661f7411145659fb8c954aac/index.js#L55

to 

``` js
app.listen(process.env.PORT || 4000)...
```

**Comment by schersh** [comment]
Okay, made that change, but still getting the same three errors referencing favicon and the get / error.  Connection refused at the 127.0...

**Comment by jshawl** [comment]
can you paste the entire output of `heroku logs`?

**Comment by schersh** [comment]
Sure - 

```
2015-12-10T16:11:39.644718+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-10T16:11:41.702809+00:00 heroku[web.1]: Starting process with command `node index.js`
2015-12-10T16:11:45.024097+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-12-10T16:11:45.024118+00:00 app[web.1]: memory, and will not scale past a single process.
2015-12-10T16:11:45.053595+00:00 app[web.1]: app listening on port 4000
2015-12-10T16:11:45.024117+00:00 app[web.1]: designed for a production environment, as it will leak
2015-12-10T16:11:45.099750+00:00 app[web.1]:                                       ^
2015-12-10T16:11:45.099785+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-12-10T16:11:45.099727+00:00 app[web.1]: 
2015-12-10T16:11:45.099787+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2015-12-10T16:11:45.099747+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-12-10T16:11:45.099800+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-10T16:11:45.099750+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-10T16:11:45.099788+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2015-12-10T16:11:46.053031+00:00 heroku[web.1]: Process exited with status 1
2015-12-10T16:11:46.072598+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-10T16:11:46.071310+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-10T16:11:49.993733+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-12-10T16:11:49.993746+00:00 app[web.1]: memory, and will not scale past a single process.
2015-12-10T16:11:49.993744+00:00 app[web.1]: designed for a production environment, as it will leak
2015-12-10T16:11:50.017968+00:00 app[web.1]: app listening on port 4000
2015-12-10T16:11:50.919367+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-10T16:11:47.700339+00:00 heroku[web.1]: Starting process with command `node index.js`
2015-12-10T16:11:47.700339+00:00 heroku[web.1]: Starting process with command `node index.js`
2015-12-10T16:11:50.042640+00:00 app[web.1]:                                       ^
2015-12-10T16:11:50.042535+00:00 app[web.1]: 
2015-12-10T16:11:50.042673+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2015-12-10T16:11:50.042636+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-12-10T16:11:50.042639+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-10T16:11:50.042672+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-12-10T16:11:50.042687+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-10T16:11:50.042674+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2015-12-10T16:11:50.042535+00:00 app[web.1]: 
2015-12-10T16:11:50.042636+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-12-10T16:11:50.042673+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2015-12-10T16:11:50.042640+00:00 app[web.1]:                                       ^
2015-12-10T16:11:50.042639+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-10T16:11:50.042672+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-12-10T16:11:50.042687+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-10T16:11:50.042674+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2015-12-10T16:11:51.581497+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=enigmatic-caverns-6880.herokuapp.com request_id=678192e0-ed50-4bf7-9365-98e634557cd5 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:11:51.882094+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=enigmatic-caverns-6880.herokuapp.com request_id=fd43f10d-f5b0-471b-9f3d-7c5a789a61a1 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:11:50.905198+00:00 heroku[web.1]: Process exited with status 1
2015-12-10T16:11:52.557162+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=enigmatic-caverns-6880.herokuapp.com request_id=74958116-c4a0-4250-8ecb-1d3049eecdbd fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-10T16:12:35.354793+00:00 heroku[run.8412]: Starting process with command `node index.js`
2015-12-10T16:12:35.326816+00:00 heroku[run.8412]: Awaiting client
2015-12-10T16:12:35.724411+00:00 heroku[run.8412]: State changed from starting to up
2015-12-10T16:12:38.199964+00:00 heroku[run.8412]: Process exited with status 1
2015-12-10T16:12:38.222228+00:00 heroku[run.8412]: State changed from up to complete
```

**Comment by jshawl** [comment]
can you change https://github.com/schersh/Travel_app_project_3/blob/20227c841312eeda661f7411145659fb8c954aac/db/schema.js#L5

to `process.env.MONGOLAB_URI`?

also what is the output of `heroku config`? don't paste here, but is MONGOLAB_URI there?

**Comment by schersh** [comment]
Sorry - now were are back to just getting the favicon error again

**Comment by schersh** [comment]
Yes, the mongolab_uri is there in the output. We changed that syntax in the schema, now trying to run the node db/seeds.js

**Comment by schersh** [comment]
Error now reads: 

```
Running node db/seeds.js on enigmatic-caverns-6880... up, run.1681

/app/node_modules/mongodb/lib/server.js:235
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

**Comment by jshawl** [comment]
https://github.com/schersh/Travel_app_project_3/blob/20227c841312eeda661f7411145659fb8c954aac/db/schema.js#L5 should be `MONGOLAB_URI`

**Comment by schersh** [comment]
Sorry, Cassidy hasn't pushed up to github the changes we've been making, he'll do that now. He had already changed that line.

**Comment by jshawl** [comment]
ok let me know

**Comment by schersh** [comment]
The github repo is up to date with what we've tried: https://github.com/schersh/Travel_app_project_3/tree/deployment-test 
But our error trace doesn't seem to be changing - could this be an issue with how our database is provisioned or our add-ons?

**Comment by jshawl** [comment]
https://github.com/schersh/Travel_app_project_3/blob/8c389f05cf058f6cdc40e07a209d8f28f98d28a5/db/schema.js#L3 still references localhost. should include MONGOLAB_URI

**Comment by schersh** [comment]
Are you looking at the deployment_test branch? https://github.com/schersh/Travel_app_project_3/blob/deployment-test/db/schema.js 
We do have the MONGOLAB_URI

```
var conn = mongoose.connect(processs.env.MONGOLAB_URI || 'mongodb://127.0.0.1:27017/');
```

**Comment by jshawl** [comment]
I feel like you have two different mongoose connections https://github.com/schersh/Travel_app_project_3/blob/deployment-test/db/seeds.js#L3

**Comment by jshawl** [comment]
check out https://github.com/ga-dc/tunr_mongo_oojs/blob/master/db/seeds.js#L3

**Comment by schersh** [comment]
Ok, since tunr isn't a deployed app - just want to confirm - should the 

```
var mongoose = require('mongoose')
var mongodURI = ...
var conn = mongoose.connect(processs.env.MONGOLAB_URI || 'mongodb://127.0.0.1:27017/');
```

still be in the schema.js, and then the 

```
var db = mongoose.connection
var mongoose = requires('mongoose')
```

is in seeds.js?

**Comment by jshawl** [comment]
I think so but honestly the `Error: connect ECONNREFUSED 127.0.0.1:27017` in the errors means you're trying to connect to localhost somewhere instead of mongolab_uri

**Comment by schersh** [comment]
Ok, I will do a search for localhost after lunch. Thanks.

**Comment by RobertAKARobin** [comment]
It's been a while so I'm going to close this. Feel free to open a new one!
