### ISSUE TITLE
User Authorization and HBS

### ISSUE THREAD

**Issue by aoave** [ga-wdi-exercises/project3#108]
I am trying to get User Auth to work but  I am getting an error to do with flash message. I have sessions installed is the strange thing. Not sure what could be triggering that message.

``` /Users/Ao/wdi/projects/SwoleMate/node_modules/connect-flash/lib/flash.js:60
  if (this.session === undefined) throw Error('req.flash() requires sessions');
                                  ^

Error: req.flash() requires sessions
    at Error (native)
    at IncomingMessage._flash [as flash] (/Users/Ao/wdi/projects/SwoleMate/node_modules/connect-flash/lib/flash.js:60:41)
    at Query.<anonymous> (/Users/Ao/wdi/projects/SwoleMate/config/passport.js:59:42)
    at /Users/Ao/wdi/projects/SwoleMate/node_modules/kareem/index.js:177:19
    at /Users/Ao/wdi/projects/SwoleMate/node_modules/kareem/index.js:109:16
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

**Comment by jshawl** [comment]
https://github.com/ga-dc/project3/issues/97#issuecomment-163646087

**Comment by aoave** [comment]
Well some progress my but, now my login doesn't take me back to my home page after login and my terminal is yelling this at me
```express-session deprecated undefined resave option; provide resave option app.js:24:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:24:9
events.js:141

``````

I googled it and I saw people had done this:
```app.use(session({
    secret: cookie_secret,
    name: cookie_name,
    store: sessionStore, // connect-mongo session store
    proxy: true,
    resave: true,
    saveUninitialized: true
}));```

When I put that resave and saveUninitialized in I am getting:
```[nodemon] starting `node app.js`
/Users/Ao/wdi/projects/SwoleMate/app.js:25
                  resave: false,
                  ^^^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
``````

**Comment by jshawl** [comment]
I think you're missing a comma before the `resave:` line

**Comment by RobertAKARobin** [comment]
It's been 20 minutes, so I'm going to close this. Feel free to open a new one!
