### ISSUE TITLE
cannot run seeds file on heroku

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project3#118]
```
Oops! Mongo threw an error. Is `mongod` running?
connect ECONNREFUSED 127.0.0.1:27017
```

**Comment by RobertAKARobin** [comment]
It shouldn't be using `127.0.0.1:27107`. This indicates that it's not using that environment variable you put in there. Since you're using `mean.io` I'm not sure how to troubleshoot this. I'd say anywhere you see `mongodb://`, replace it with the line you put in your `production.js` file -- something like:

```
process.env.MONGODB_URL || "mongodb://localhost/mean-bnb"
```

Also, make sure when you run `heroku config`, it prints out that MongoLab URL.

**Comment by adambray** [comment]
Is your seed script connecting to mongo over localhost? If so, you need to update the db connect url to be the Heroku version.

**Comment by adambray** [comment]
What @RobertAKARobin said. He said it smarter-like.

**Comment by codedre** [comment]
not using mean.io but here is my seeds.js file

``` js
require("./schema");
var mongoose = require("mongoose");
mongoose.createConnection(process.env.MONGOLAB_URI || 'mongodb://localhost/beacon');
var db = mongoose.connection;
var userData = require("./user_data");


// TODO Why is error a string here? Will err.message be logged?
db.on("error", function(err){
  console.log("Oops! Mongo threw an error. Is `mongod` running?");
  console.log(err.message);
  process.exit();
});

db.once("open", function () {
  console.log("Connected to the database.");
  var User = require("../models/user");

  User.remove({}).then(function(){
    forEach(userData, function(userDatum){
      return new User(userDatum).save();
    }).then(function(){
      process.exit();
    });
  });
});

function forEach(collection, callback, index){
  if(!index) index = 0;
  return callback(collection[index]).then(function(){
    if(collection[index + 1]) return forEach(collection, callback, index + 1);
  });
}
```

**Comment by RobertAKARobin** [comment]
Gah, I'm sorry, I got you mixed up with another student! :P

**Comment by RobertAKARobin** [comment]
What happens when you run `heroku config`?

**Comment by codedre** [comment]
Mixed up?!?!?!?!?! I'm the one and only lol

```
$ heroku config
=== beacon-wdi Config Vars
MONGOLAB_URI:        mongodb://heroku_qd54ghm2:449303bohtl0ur1ok574l11lh@ds041924.mongolab.com:41924/heroku_qd54ghm2
facebookCallbackURL: https://beacon-wdi.herokuapp.com/auth/facebook/callback
facebookID:          1048856355144689
facebookSecret:      ae8e9526782365b5db89456f0b8e3392
googleCallbackURL:   http://beacon-wdi.herokuapp.com/auth/google/callback
googleID:            212938430026-m45anubk7pdr9qlnfttfniv2qnvr6n95.apps.googleusercontent.com
googleSecret:        fiTFY2az5glo8JZRBq-aGmKg
```

**Comment by adambray** [comment]
Hmm, that looks correct to me at first glance. Are you sure you've committed and pushed all updates to heroku master before running `heroku run node db/seeds.js`

**Comment by RobertAKARobin** [comment]
I just talked with Jorge, and for some reason read your name as his.

Instead of `mongoose.createConnection`, try `mongoose.connect`.

**Comment by codedre** [comment]
Yes sir @adambray 
 and this is what it says now @RobertAKARobin 

```
heroku run node db/seeds.js
Running node db/seeds.js on beacon-wdi... up, run.1929
/app/db/seeds.js:3
mongoose.connection(process.env.MONGOLAB_URI || 'mongodb://localhost/beacon');
         ^

TypeError: mongoose.connection is not a function
    at Object.<anonymous> (/app/db/seeds.js:3:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by RobertAKARobin** [comment]
`mongoose.connect`, not `.connection`

**Comment by codedre** [comment]
seeds file again

```
require("./schema");
var mongoose = require("mongoose");
mongoose.connect(process.env.MONGOLAB_URI || 'mongodb://localhost/beacon');
var db = mongoose.connection;
var userData = require("./user_data");


// TODO Why is error a string here? Will err.message be logged?
db.on("error", function(err){
  console.log("Oops! Mongo threw an error. Is `mongod` running?");
  console.log(err.message);
  process.exit();
});

db.once("open", function () {
  console.log("Connected to the database.");
  var User = require("../models/user");

  User.remove({}).then(function(){
    forEach(userData, function(userDatum){
      return new User(userDatum).save();
    }).then(function(){
      process.exit();
    });
  });
});

function forEach(collection, callback, index){
  if(!index) index = 0;
  return callback(collection[index]).then(function(){
    if(collection[index + 1]) return forEach(collection, callback, index + 1);
  });
}
```

```
heroku run node db/seeds.js
Running node db/seeds.js on beacon-wdi... up, run.2392
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Trying to open unclosed connection.
    at NativeConnection.Connection.open (/app/node_modules/mongoose/lib/connection.js:226:15)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:229:15)
    at Object.<anonymous> (/app/db/seeds.js:3:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by RobertAKARobin** [comment]
Put the `.connect` in your schema file, and your schema file only.
