### ISSUE TITLE
Pushing To Heroku

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-wdi-exercises/project3#127]
I'm getting a long error where i'm getting an error at npm start

**Comment by KoryJCampbell** [comment]
```
2015-12-11T15:45:35.980212+00:00 heroku[api]: Deploy b9adb98 by koryjcampbell@gmail.com
2015-12-11T15:45:35.980212+00:00 heroku[api]: Release v6 created by koryjcampbell@gmail.com
2015-12-11T15:45:36.124632+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T15:45:36.124639+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-11T15:45:36.500314+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T15:45:38.419672+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-11T15:45:41.517214+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-11T15:45:41.517734+00:00 app[web.1]: npm ERR! node v5.1.1
2015-12-11T15:45:41.518338+00:00 app[web.1]: npm ERR! npm  v3.3.12
2015-12-11T15:45:41.516171+00:00 app[web.1]: npm ERR! Linux 3.13.0-71-generic
2015-12-11T15:45:41.520542+00:00 app[web.1]:
2015-12-11T15:45:41.520768+00:00 app[web.1]: npm ERR! missing script: start
2015-12-11T15:45:41.520974+00:00 app[web.1]: npm ERR!
2015-12-11T15:45:41.521128+00:00 app[web.1]: npm ERR! If you need help, you may report this error at:
2015-12-11T15:45:41.521274+00:00 app[web.1]: npm ERR!     <https://github.com/npm/npm/issues>
2015-12-11T15:45:41.528018+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-11T15:45:41.527777+00:00 app[web.1]:
2015-12-11T15:45:41.528162+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-11T15:45:42.224125+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T15:45:42.243442+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T15:46:34.518877+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hackerbnb.herokuapp.com request_id=8dfa8192-ba5f-486c-9672-0e249c78a93a fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T15:46:35.271676+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hackerbnb.herokuapp.com request_id=4fafa1ce-beef-4270-b71e-66a3d42164f9 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T15:46:36.012677+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hackerbnb.herokuapp.com request_id=15e3893d-fd00-4be5-b2da-f1ceee7000bf fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T15:46:36.621405+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hackerbnb.herokuapp.com request_id=d8d41039-b027-4ac4-8b2b-ea8075258a07 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T15:46:37.615985+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hackerbnb.herokuapp.com request_id=9bd07f31-43b3-4b61-a72e-c0ed0f09b9d5 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T15:46:37.901367+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hackerbnb.herokuapp.com request_id=20c06982-4ec5-4bd9-a1b8-b4a7b2b0707c fwd="50.200.196.50" dyno= connect= service= status=503 bytes=

```

**Comment by RobertAKARobin** [comment]
Try walking through the steps in this article:

https://devcenter.heroku.com/articles/getting-started-with-nodejs

In particular, pay attention to the part about the Procfile and environment variables.

**Comment by KoryJCampbell** [comment]
I defined the procfile as 

```
web: node app.js
```

but i'm still getting the same error

**Comment by RobertAKARobin** [comment]
Could you push your code up to Github so I can look?

**Comment by KoryJCampbell** [comment]
https://github.com/KoryJCampbell/hackerbnb

**Comment by RobertAKARobin** [comment]
What is `open.procfile`? The procfile should be named just `Procfile`, with no file extension.

**Comment by KoryJCampbell** [comment]
just pushed it up, and getting the same error

**Comment by RobertAKARobin** [comment]
One problem is that you're including your node modules in your Github repo. Create a file called `.gitignore`. Inside it, put the line `node_modules`. Then, `git rm -r --cached node_modules`. Then, add and commit. You'll see a lot of "delete" messages, but don't worry, this is just keeping the modules from being tracked by Git -- they'll stay on your computer.

**Comment by KoryJCampbell** [comment]
Ok that worked, but it through a new error

```
2015-12-11T16:43:10.674068+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T16:43:10.674078+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-11T16:43:10.567043+00:00 heroku[api]: Release v9 created by koryjcampbell@gmail.com
2015-12-11T16:43:10.566971+00:00 heroku[api]: Deploy c650553 by koryjcampbell@gmail.com
2015-12-11T16:43:10.699696+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T16:43:12.691906+00:00 heroku[web.1]: Starting process with command `node app.js`
2015-12-11T16:43:14.525096+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-12-11T16:43:14.523729+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-12-11T16:43:14.837791+00:00 app[web.1]: designed for a production environment, as it will leak
2015-12-11T16:43:14.837792+00:00 app[web.1]: memory, and will not scale past a single process.
2015-12-11T16:43:14.837788+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-12-11T16:43:14.880143+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2015-12-11T16:43:14.880144+00:00 app[web.1]:       ^
2015-12-11T16:43:14.880145+00:00 app[web.1]:
2015-12-11T16:43:14.880147+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:25)
2015-12-11T16:43:14.880150+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
2015-12-11T16:43:14.880148+00:00 app[web.1]:     at emitThree (events.js:97:13)
2015-12-11T16:43:14.880151+00:00 app[web.1]:     at emitTwo (events.js:87:13)
2015-12-11T16:43:14.880137+00:00 app[web.1]: events.js:141
2015-12-11T16:43:14.880146+00:00 app[web.1]: Error: failed to connect to [localhost:27017]
2015-12-11T16:43:14.880155+00:00 app[web.1]:     at doNTCallback2 (node.js:452:9)
2015-12-11T16:43:14.880151+00:00 app[web.1]:     at emit (events.js:172:7)
2015-12-11T16:43:14.880153+00:00 app[web.1]:     at emitOne (events.js:77:13)
2015-12-11T16:43:14.880154+00:00 app[web.1]:     at emitErrorNT (net.js:1253:8)
2015-12-11T16:43:14.880153+00:00 app[web.1]:     at Socket.emit (events.js:169:7)
2015-12-11T16:43:14.880149+00:00 app[web.1]:     at emit (events.js:175:7)
2015-12-11T16:43:14.880152+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
2015-12-11T16:43:14.880156+00:00 app[web.1]:     at process._tickCallback (node.js:366:17)
2015-12-11T16:43:15.615429+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T16:43:15.629402+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T16:43:43.175295+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hackerbnb.herokuapp.com request_id=449b167d-6b94-4d0c-829c-a8bb46adb209 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:43:44.120215+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hackerbnb.herokuapp.com request_id=ac765131-651b-4ad2-b054-882338f1a6fd fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:43:45.878436+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hackerbnb.herokuapp.com request_id=68278f65-d227-4ae7-875d-10d9e3eb2c95 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:43:46.623283+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hackerbnb.herokuapp.com request_id=69c0d315-b807-4ff7-8c8a-7b7688b1df5b fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:45:41.455214+00:00 heroku[api]: Deploy 22c822a by koryjcampbell@gmail.com
2015-12-11T16:45:41.455214+00:00 heroku[api]: Release v10 created by koryjcampbell@gmail.com
2015-12-11T16:45:41.609352+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T16:45:41.609357+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-11T16:45:53.890262+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T16:45:55.410728+00:00 heroku[web.1]: Starting process with command `node app.js`
2015-12-11T16:45:57.967588+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-12-11T16:45:57.969218+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-12-11T16:45:58.520220+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-12-11T16:45:58.520225+00:00 app[web.1]: designed for a production environment, as it will leak
2015-12-11T16:45:58.520226+00:00 app[web.1]: memory, and will not scale past a single process.
2015-12-11T16:45:58.572650+00:00 app[web.1]: events.js:141
2015-12-11T16:45:58.572654+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2015-12-11T16:45:58.572655+00:00 app[web.1]:       ^
2015-12-11T16:45:58.572656+00:00 app[web.1]:
2015-12-11T16:45:58.572657+00:00 app[web.1]: Error: failed to connect to [localhost:27017]
2015-12-11T16:45:58.572658+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:25)
2015-12-11T16:45:58.572658+00:00 app[web.1]:     at emitThree (events.js:97:13)
2015-12-11T16:45:58.572659+00:00 app[web.1]:     at emit (events.js:175:7)
2015-12-11T16:45:58.572660+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
2015-12-11T16:45:58.572661+00:00 app[web.1]:     at emitTwo (events.js:87:13)
2015-12-11T16:45:58.572662+00:00 app[web.1]:     at emit (events.js:172:7)
2015-12-11T16:45:58.572666+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
2015-12-11T16:45:58.572667+00:00 app[web.1]:     at emitOne (events.js:77:13)
2015-12-11T16:45:58.572668+00:00 app[web.1]:     at Socket.emit (events.js:169:7)
2015-12-11T16:45:58.572669+00:00 app[web.1]:     at emitErrorNT (net.js:1253:8)
2015-12-11T16:45:58.572670+00:00 app[web.1]:     at doNTCallback2 (node.js:452:9)
2015-12-11T16:45:58.572670+00:00 app[web.1]:     at process._tickCallback (node.js:366:17)
2015-12-11T16:45:59.509917+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T16:45:59.476428+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T16:46:00.416094+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hackerbnb.herokuapp.com request_id=ffe83751-e61d-42fe-8040-ccb5d30195cc fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:46:01.198094+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hackerbnb.herokuapp.com request_id

```

**Comment by RobertAKARobin** [comment]
Take a look at what I just posted in the student group Slack.

**Comment by KoryJCampbell** [comment]
no luck still
