### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by aoave** [ga-wdi-exercises/project3#129]
Deploying to heroku and I am getting this error in my package.json 

Its giving me this:

```
remote: -----> Node.js app detected
remote: parse error: Invalid numeric literal at line 29, column 8
remote:  !     Unable to parse package.json
remote: 
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to powerful-journey-2894.
remote: 
```

**Comment by aoave** [comment]
Specifically  at the morgan line "homepage": "https://github.com/murgia/SwoleMate#readme",

```
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.14.1",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.4.0",
    "express": "^4.13.3",
    "express-session": "^1.12.1",
    "hbs": "^4.0.0",
    "method-override": "^2.3.5",
    "mongoose": "^4.2.9",
    "morgan": "^1.6.1",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0"
  }
```

**Comment by RobertAKARobin** [comment]
Weird! Delete that line and see what happens.

**Comment by aoave** [comment]
Okay Should I also unrequire it I dont want it to break my user auth

**Comment by RobertAKARobin** [comment]
Hang on a sec, I'm going to try this on my compy

**Comment by RobertAKARobin** [comment]
Which branch are you using?

**Comment by aoave** [comment]
I just updated both mine and the master

**Comment by RobertAKARobin** [comment]
I'm trying some things. In the meantime:
- Get that `process.env.MONGOLAB_URI` thing up and running
- Add a Procfile: https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-a-procfile
- Change `app.listen(3000` to `app.listen(process.env.PORT || 3000`

**Comment by RobertAKARobin** [comment]
That should be it! https://swoleapp-robin.herokuapp.com/

**Comment by aoave** [comment]
Okay I got it to deploy but when I am opening the app is failing to launch

**Comment by aoave** [comment]
But you got it working? What could I be missing?

**Comment by RobertAKARobin** [comment]
What does `heroku logs -t` say?

**Comment by aoave** [comment]
```
Aurelios-MacBook-Pro:SwoleMate Ao$ heroku logs -t
2015-12-11T15:56:35.716197+00:00 heroku[api]: Enable Logplex by aavelley@gmail.com
2015-12-11T15:56:35.716197+00:00 heroku[api]: Release v2 created by aavelley@gmail.com
2015-12-11T16:01:32.602084+00:00 heroku[api]: Attach MONGOLAB resource by aavelley@gmail.com
2015-12-11T16:01:32.602084+00:00 heroku[api]: Release v3 created by aavelley@gmail.com
2015-12-11T16:05:27.562572+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T16:05:27.562592+00:00 heroku[slug-compiler]: Slug compilation failed: failed to compile Node.js app
2015-12-11T16:09:03.421534+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T16:09:03.421544+00:00 heroku[slug-compiler]: Slug compilation failed: failed to compile Node.js app
2015-12-11T16:32:43.866648+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T16:32:43.866658+00:00 heroku[slug-compiler]: Slug compilation failed: failed to compile Node.js app
2015-12-11T16:39:44.684333+00:00 heroku[api]: Deploy 1710eee by aavelley@gmail.com
2015-12-11T16:39:44.684396+00:00 heroku[api]: Release v4 created by aavelley@gmail.com
2015-12-11T16:39:44.620894+00:00 heroku[api]: Scale to web=1 by aavelley@gmail.com
2015-12-11T16:39:45.023440+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T16:39:45.023444+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-11T16:39:45.908215+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-11T16:39:48.370625+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-11T16:39:48.371055+00:00 app[web.1]: npm ERR! node v5.1.1
2015-12-11T16:39:48.371451+00:00 app[web.1]: npm ERR! npm  v3.3.12
2015-12-11T16:39:48.373062+00:00 app[web.1]: 
2015-12-11T16:39:48.373245+00:00 app[web.1]: npm ERR! missing script: start
2015-12-11T16:39:48.373426+00:00 app[web.1]: npm ERR! 
2015-12-11T16:39:48.373428+00:00 app[web.1]: npm ERR! If you need help, you may report this error at:
2015-12-11T16:39:48.373508+00:00 app[web.1]: npm ERR!     <https://github.com/npm/npm/issues>
2015-12-11T16:39:48.379073+00:00 app[web.1]: 
2015-12-11T16:39:48.379255+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-11T16:39:48.379390+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-11T16:39:48.369821+00:00 app[web.1]: npm ERR! Linux 3.13.0-71-generic
2015-12-11T16:39:49.003233+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T16:39:49.042625+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T16:39:49.044061+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T16:39:49.894010+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-11T16:39:51.397387+00:00 app[web.1]: npm ERR! Linux 3.13.0-71-generic
2015-12-11T16:39:51.397875+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-11T16:39:51.398118+00:00 app[web.1]: npm ERR! node v5.1.1
2015-12-11T16:39:51.398593+00:00 app[web.1]: npm ERR! npm  v3.3.12
2015-12-11T16:39:51.399701+00:00 app[web.1]: 
2015-12-11T16:39:51.400020+00:00 app[web.1]: npm ERR! 
2015-12-11T16:39:51.399852+00:00 app[web.1]: npm ERR! missing script: start
2015-12-11T16:39:51.404817+00:00 app[web.1]: 
2015-12-11T16:39:51.400110+00:00 app[web.1]: npm ERR! If you need help, you may report this error at:
2015-12-11T16:39:51.400215+00:00 app[web.1]: npm ERR!     <https://github.com/npm/npm/issues>
2015-12-11T16:39:51.405084+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-11T16:39:51.404983+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-11T16:39:51.956801+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T16:39:51.992843+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T16:40:33.777410+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=powerful-journey-2894.herokuapp.com request_id=2828225a-8c4c-48e9-b1a8-32e9ffe4d381 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:40:33.958413+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=powerful-journey-2894.herokuapp.com request_id=d51950b7-a715-45f0-aca0-c3b281c6567a fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:42:50.734842+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=powerful-journey-2894.herokuapp.com request_id=d3a18368-c095-458d-b0c1-73048d3aa1c9 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:42:50.568827+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=powerful-journey-2894.herokuapp.com request_id=083075fb-77de-406a-93df-f49e80a9e703 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:44:16.809404+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=powerful-journey-2894.herokuapp.com request_id=ab0dd0b4-8174-47dd-a848-ecf15554da1a fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:44:16.977207+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=powerful-journey-2894.herokuapp.com request_id=51530074-ecd1-411c-907f-2d2b0dc3d513 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:45:34.500423+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T16:45:34.500432+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-11T16:45:34.327704+00:00 heroku[api]: Deploy 7179fd7 by aavelley@gmail.com
2015-12-11T16:45:34.327704+00:00 heroku[api]: Release v5 created by aavelley@gmail.com
2015-12-11T16:45:36.290968+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T16:45:37.237727+00:00 heroku[web.1]: Starting process with command `node app.js`
2015-12-11T16:45:39.325311+00:00 app[web.1]: /app/app.js:20
2015-12-11T16:45:39.325325+00:00 app[web.1]: app.use(morgan('dev'));
2015-12-11T16:45:39.325326+00:00 app[web.1]:         ^
2015-12-11T16:45:39.325327+00:00 app[web.1]: 
2015-12-11T16:45:39.325328+00:00 app[web.1]: ReferenceError: morgan is not defined
2015-12-11T16:45:39.325329+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:20:9)
2015-12-11T16:45:39.325329+00:00 app[web.1]:     at Module._compile (module.js:425:26)
2015-12-11T16:45:39.325331+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-12-11T16:45:39.325331+00:00 app[web.1]:     at Function.Module._load (module.js:313:12)
2015-12-11T16:45:39.325330+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-11T16:45:39.325333+00:00 app[web.1]:     at startup (node.js:138:18)
2015-12-11T16:45:39.325332+00:00 app[web.1]:     at Function.Module.runMain (module.js:457:10)
2015-12-11T16:45:39.325333+00:00 app[web.1]:     at node.js:974:3
2015-12-11T16:45:40.138270+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T16:45:40.126868+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T16:45:41.649851+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=powerful-journey-2894.herokuapp.com request_id=f55ce9f8-cbcc-479b-9d6f-4f7aa9d5a2d9 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T16:45:41.439983+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=powerful-journey-2894.herokuapp.com request_id=f7b486a3-41bf-40bf-b58e-04df9cd71e07 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
```

**Comment by RobertAKARobin** [comment]
https://github.com/murgia/SwoleMate/pull/25

**Comment by RobertAKARobin** [comment]
And maybe put that line back into your package.json if you removed it

**Comment by aoave** [comment]
Added that line back in, I have made all your changes and still nothing

**Comment by RobertAKARobin** [comment]
Did you do the whole `heroku config:set` thing?

**Comment by aoave** [comment]
Did do that got it up now our seeds wont work. First we got this error

```
Running node db/seeds.js on powerful-journey-2894... up, run.3322
/app/db/seeds.js:6
db.on("error", function(err){
   ^

TypeError: db.on is not a function
    at Object.<anonymous> (/app/db/seeds.js:6:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

I changed `var db = mongoose.connect(process.env.MONGOLAB_URI ||mongodbUri);` to `var db =mongoose.connect` and it said it seeded after that but now they will not populate on the page

**Comment by RobertAKARobin** [comment]
Move these...

```
var mongodbUri = 'mongodb://localhost/Swolemate2';
mongoose.connect(process.env.MONGOLAB_URI ||mongodbUri);
```

...from your `app.js` to your `schema.js`. Your seeds file doesn't (and shouldn't) require your `app.js`, which is where the connection currently is.

**Comment by aoave** [comment]
Alright that got the seeds in but now the app is spitting error in browser

**Comment by RobertAKARobin** [comment]
Are the seeds working?

**Comment by aoave** [comment]
Got it thank you we had to take the // mongoose.connect(process.env.MONGOLAB_URI ||mongodbUri);

**Comment by aoave** [comment]
out of the schema

**Comment by aoave** [comment]
But its not letting us use the api womp womp womp

**Comment by RobertAKARobin** [comment]
Just present on localhost.
