### ISSUE TITLE
heroku crash issues

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project3#130]
deployed on herokue and getting the following crash. Can you please help us?

Thank you.

```
2015-12-11T17:14:35.721101+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=campaign-finance.herokuapp.com request_id=194de496-77d1-4c7e-877e-cee7a2ae36d2 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T17:14:36.190547+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=campaign-finance.herokuapp.com request_id=9328b6c7-d7a7-49f0-8b63-f68f177a931d fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
Wonsiks-MacBook-Pro:project3 wonsikjeong$
```

**Comment by RobertAKARobin** [comment]
There could be a lot of different things causing this. Check out what I put in Slack:

https://ga-students.slack.com/archives/wdi-dc-7-students/p1449852734003508

**Comment by onesick** [comment]
One more question!

``` js
Candidate.fetch = function(){
 var url="http://localhost:3000/data";
  // saving the ajax request to a local variable
  var request = $.getJSON(url)
  // the promise function on a successful ajax call.
  .then(function(response) {
    // local variable in the promise callback instantiated as an empty array
    var candidates = [];
    // loop over each element in the response
    for(var i = 0; i < response.length; i++){

      // create a new JS candidate object for each element in the response
      candidates.push(new Candidate(response[i]));
    }
    // returns candidates in the promise so that it can be passed in as an argument to future promises
    return candidates;
  })
  .fail(function(response){
    console.log("candidates fetch fail")
  })
  // explicit return of the fetch function that returns the json request with artists available an argument for future promises
  return request
};
```

in this case, is there a way that we can know what base URL we are on? can we do something like "./data"?

**Comment by onesick** [comment]
when we are on Herokue, the url is no longer local host

**Comment by RobertAKARobin** [comment]
Yep, `"./data" or "/data" should work!

**Comment by onesick** [comment]
what about env files? since it's git ignored, they can't find on heroku

**Comment by onesick** [comment]
nvm. I'm reading this: https://devcenter.heroku.com/articles/config-vars
please let me know if i'm reading a wrong doc

**Comment by RobertAKARobin** [comment]
Take a look at that Slack message again. It's the `heroku config:set` thing.

**Comment by onesick** [comment]
I successfully deployed on herokue, but we lost all the fonts and data. What could cause the problem?

**Comment by onesick** [comment]
https://campaign-finance.herokuapp.com/

**Comment by RobertAKARobin** [comment]
Looks fine to me?

**Comment by RobertAKARobin** [comment]
Check your `heroku logs -t`. I'm not sure why `https://campaign-finance.herokuapp.com/data` isn't working.

**Comment by onesick** [comment]
```
015-12-11T17:29:30.069460+00:00 app[web.1]:     at Module._compile (module.js:425:26)
2015-12-11T17:29:30.069460+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-11T17:29:30.069461+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-12-11T17:29:30.069462+00:00 app[web.1]:     at Function.Module._load (module.js:313:12)
2015-12-11T17:29:30.069462+00:00 app[web.1]:     at Function.Module.runMain (module.js:457:10)
2015-12-11T17:29:30.069463+00:00 app[web.1]:     at startup (node.js:138:18)
2015-12-11T17:29:30.069464+00:00 app[web.1]:     at node.js:974:3
2015-12-11T17:29:30.856627+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T17:29:30.895522+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T17:29:30.896960+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T17:29:24.368983+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T17:29:32.317015+00:00 heroku[web.1]: Starting process with command `node index.js`
2015-12-11T17:29:35.562916+00:00 app[web.1]: module.js:340
2015-12-11T17:29:35.562926+00:00 app[web.1]:     throw err;
2015-12-11T17:29:35.562927+00:00 app[web.1]:     ^
2015-12-11T17:29:35.562928+00:00 app[web.1]:
2015-12-11T17:29:35.562933+00:00 app[web.1]: Error: Cannot find module './env'
2015-12-11T17:29:35.562934+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2015-12-11T17:29:35.562935+00:00 app[web.1]:     at Function.Module._load (module.js:289:25)
2015-12-11T17:29:35.562935+00:00 app[web.1]:     at Module.require (module.js:366:17)
2015-12-11T17:29:35.562936+00:00 app[web.1]:     at require (module.js:385:17)
2015-12-11T17:29:35.562937+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:14:9)
2015-12-11T17:29:35.562937+00:00 app[web.1]:     at Module._compile (module.js:425:26)
2015-12-11T17:29:35.562938+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-11T17:29:35.562939+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-12-11T17:29:35.562939+00:00 app[web.1]:     at Function.Module._load (module.js:313:12)
2015-12-11T17:29:35.562940+00:00 app[web.1]:     at Function.Module.runMain (module.js:457:10)
2015-12-11T17:29:35.562941+00:00 app[web.1]:     at startup (node.js:138:18)
2015-12-11T17:29:35.562942+00:00 app[web.1]:     at node.js:974:3
2015-12-11T17:29:36.367400+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T17:29:36.355322+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T17:29:36.689048+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=campaign-finance.herokuapp.com request_id=8cc31514-5f14-4c3f-aa0b-a891a69be4b7 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T17:29:37.662075+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=campaign-finance.herokuapp.com request_id=e4fa73e9-d73b-4115-993a-4dd7394819f9 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2015-12-11T17:37:21.070228+00:00 heroku[api]: Set api_key config vars by wsjeong21@hotmail.com
2015-12-11T17:37:21.070264+00:00 heroku[api]: Release v5 created by wsjeong21@hotmail.com
2015-12-11T17:37:22.392336+00:00 heroku[web.1]: Starting process with command `node index.js`
2015-12-11T17:37:21.192620+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T17:37:24.687744+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2015-12-11T17:37:24.687742+00:00 app[web.1]:     ^
2015-12-11T17:37:24.687731+00:00 app[web.1]: module.js:340
2015-12-11T17:37:24.687744+00:00 app[web.1]: Error: Cannot find module './env'
2015-12-11T17:37:24.687741+00:00 app[web.1]:     throw err;
2015-12-11T17:37:24.687745+00:00 app[web.1]:     at Function.Module._load (module.js:289:25)
2015-12-11T17:37:24.687750+00:00 app[web.1]:     at Function.Module.runMain (module.js:457:10)
2015-12-11T17:37:24.687747+00:00 app[web.1]:     at Module._compile (module.js:425:26)
2015-12-11T17:37:24.687749+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-12-11T17:37:24.687747+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:14:9)
2015-12-11T17:37:24.687746+00:00 app[web.1]:     at Module.require (module.js:366:17)
2015-12-11T17:37:24.687742+00:00 app[web.1]:
2015-12-11T17:37:24.687749+00:00 app[web.1]:     at Function.Module._load (module.js:313:12)
2015-12-11T17:37:24.687748+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-11T17:37:24.687746+00:00 app[web.1]:     at require (module.js:385:17)
2015-12-11T17:37:24.687751+00:00 app[web.1]:     at startup (node.js:138:18)
2015-12-11T17:37:24.687751+00:00 app[web.1]:     at node.js:974:3
2015-12-11T17:37:25.340365+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-11T17:37:25.322806+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T17:39:07.723387+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-11T17:39:07.723396+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-11T17:39:07.571486+00:00 heroku[api]: Deploy d628584 by wsjeong21@hotmail.com
2015-12-11T17:39:07.571555+00:00 heroku[api]: Release v6 created by wsjeong21@hotmail.com
2015-12-11T17:39:07.680989+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T17:39:09.019191+00:00 heroku[web.1]: Starting process with command `node index.js`
2015-12-11T17:39:12.726826+00:00 app[web.1]: app listening on port 3000
2015-12-11T17:39:12.893806+00:00 heroku[web.1]: State changed from starting to up
2015-12-11T17:39:14.105865+00:00 heroku[router]: at=info method=GET path="/javascript/d3.js" host=campaign-finance.herokuapp.com request_id=4b7d1952-a63a-4a12-b08d-3298ca65a181 fwd="50.200.196.50" dyno=web.1 connect=1ms service=16ms status=200 bytes=417
2015-12-11T17:39:14.062678+00:00 heroku[router]: at=info method=GET path="/" host=campaign-finance.herokuapp.com request_id=74937f9f-6bc8-45e3-a399-9467f4abb119 fwd="50.200.196.50" dyno=web.1 connect=1ms service=25ms status=200 bytes=2060
2015-12-11T17:39:14.100697+00:00 heroku[router]: at=info method=GET path="/css/styles.css" host=campaign-finance.herokuapp.com request_id=b4e48d4f-e919-4d6d-a87a-588001a93839 fwd="50.200.196.50" dyno=web.1 connect=0ms service=12ms status=200 bytes=2530
2015-12-11T17:39:14.113460+00:00 heroku[router]: at=info method=GET path="/javascript/script.js" host=campaign-finance.herokuapp.com request_id=862d95b7-3475-4313-91af-dbec80de10dd fwd="50.200.196.50" dyno=web.1 connect=1ms service=2ms status=200 bytes=2571
2015-12-11T17:39:14.118994+00:00 heroku[router]: at=info method=GET path="/js/models/candidate.js" host=campaign-finance.herokuapp.com request_id=13b43816-f1ed-4f85-b834-401983a22366 fwd="50.200.196.50" dyno=web.1 connect=1ms service=2ms status=200 bytes=1635
2015-12-11T17:39:14.116228+00:00 heroku[router]: at=info method=GET path="/javascript/d3.v3.js" host=campaign-finance.herokuapp.com request_id=61e4fa59-a785-47ae-91bb-67b41f31169b fwd="50.200.196.50" dyno=web.1 connect=0ms service=25ms status=200 bytes=337965
2015-12-11T17:39:15.396117+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=campaign-finance.herokuapp.com request_id=e1d670cb-0769-42b0-9150-3e5f793391ef fwd="50.200.196.50" dyno=web.1 connect=1ms service=33ms status=404 bytes=222
2015-12-11T17:39:25.538110+00:00 heroku[router]: at=info method=GET path="/css/styles.css" host=campaign-finance.herokuapp.com request_id=474aa335-da66-42b1-9679-c77819ef0834 fwd="50.200.196.50" dyno=web.1 connect=0ms service=2ms status=304 bytes=237
2015-12-11T17:39:25.553008+00:00 heroku[router]: at=info method=GET path="/javascript/script.js" host=campaign-finance.herokuapp.com request_id=d82d1ad8-88a6-48cc-958b-384dc84730f7 fwd="50.200.196.50" dyno=web.1 connect=1ms service=3ms status=304 bytes=237
2015-12-11T17:39:25.564318+00:00 heroku[router]: at=info method=GET path="/js/models/candidate.js" host=campaign-finance.herokuapp.com request_id=84526bf2-61dd-4d58-ab54-fcb12c95a1c2 fwd="50.200.196.50" dyno=web.1 connect=1ms service=24ms status=304 bytes=237
2015-12-11T17:39:25.550832+00:00 heroku[router]: at=info method=GET path="/javascript/d3.v3.js" host=campaign-finance.herokuapp.com request_id=d00d263a-847a-498e-939e-209033cda381 fwd="50.200.196.50" dyno=web.1 connect=4ms service=5ms status=304 bytes=239
2015-12-11T17:39:25.502867+00:00 heroku[router]: at=info method=GET path="/" host=campaign-finance.herokuapp.com request_id=4f0275ee-a253-4648-a49e-12c840b6f60f fwd="50.200.196.50" dyno=web.1 connect=0ms service=5ms status=304 bytes=237
2015-12-11T17:39:25.553568+00:00 heroku[router]: at=info method=GET path="/javascript/d3.js" host=campaign-finance.herokuapp.com request_id=8636020c-6a7b-4961-8933-40adeb8ba9c5 fwd="50.200.196.50" dyno=web.1 connect=1ms service=12ms status=304 bytes=236
2015-12-11T17:39:44.388224+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=7f0bda4e-0373-482c-a5ae-2e75c7247744 fwd="50.200.196.50" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0
2015-12-11T17:39:55.640244+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=b769d106-8394-4b08-a8c2-0342d8a67663 fwd="50.200.196.50" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0
2015-12-11T17:41:01.080656+00:00 heroku[router]: at=info method=GET path="/" host=campaign-finance.herokuapp.com request_id=dc1933fb-f5a4-4546-8910-4524e29f603d fwd="52.6.158.18" dyno=web.1 connect=1ms service=10ms status=416 bytes=390
2015-12-11T17:41:01.040564+00:00 heroku[router]: at=info method=GET path="/" host=campaign-finance.herokuapp.com request_id=9fb60e0d-2a39-48b2-9306-bccabbf5ce7b fwd="54.165.66.184" dyno=web.1 connect=1ms service=11ms status=206 bytes=2107
2015-12-11T17:41:01.081432+00:00 app[web.1]:     at SendStream.error (/app/node_modules/send/index.js:245:31)
2015-12-11T17:41:01.081433+00:00 app[web.1]:     at SendStream.send (/app/node_modules/send/index.js:564:19)
2015-12-11T17:41:01.081435+00:00 app[web.1]:     at FSReqWrap.oncomplete (fs.js:82:15)
2015-12-11T17:41:01.081434+00:00 app[web.1]:     at /app/node_modules/send/index.js:669:12
2015-12-11T17:41:01.081429+00:00 app[web.1]: RangeNotSatisfiableError: Range Not Satisfiable
2015-12-11T17:45:48.110955+00:00 heroku[router]: at=info method=GET path="/" host=campaign-finance.herokuapp.com request_id=2f8f5a10-5a33-4ef7-86cd-886c2794c81d fwd="50.200.196.50" dyno=web.1 connect=0ms service=4ms status=200 bytes=2060
2015-12-11T17:45:48.339099+00:00 heroku[router]: at=info method=GET path="/css/styles.css" host=campaign-finance.herokuapp.com request_id=f6dcbd5f-6485-4a92-819a-50c534883953 fwd="50.200.196.50" dyno=web.1 connect=0ms service=2ms status=200 bytes=2530
2015-12-11T17:45:48.370453+00:00 heroku[router]: at=info method=GET path="/js/models/candidate.js" host=campaign-finance.herokuapp.com request_id=28ed2a67-4af7-4fac-9abb-4cac0918bfbe fwd="50.200.196.50" dyno=web.1 connect=0ms service=10ms status=200 bytes=1635
2015-12-11T17:45:48.369773+00:00 heroku[router]: at=info method=GET path="/javascript/d3.js" host=campaign-finance.herokuapp.com request_id=51376583-812d-44d9-9aa8-d0294fc405fc fwd="50.200.196.50" dyno=web.1 connect=1ms service=11ms status=200 bytes=417
2015-12-11T17:45:48.377138+00:00 heroku[router]: at=info method=GET path="/javascript/d3.v3.js" host=campaign-finance.herokuapp.com request_id=a52fc4a2-8e62-4bfd-85a0-06c41a26784b fwd="50.200.196.50" dyno=web.1 connect=1ms service=21ms status=200 bytes=337965
2015-12-11T17:45:48.388337+00:00 heroku[router]: at=info method=GET path="/javascript/script.js" host=campaign-finance.herokuapp.com request_id=ef109a74-145a-44f1-a429-da0d12974fed fwd="50.200.196.50" dyno=web.1 connect=1ms service=12ms status=200 bytes=2571
2015-12-11T17:45:51.220845+00:00 heroku[router]: at=info method=GET path="/css/styles.css" host=campaign-finance.herokuapp.com request_id=81d5ff02-883c-474a-9133-602c3d4d63f3 fwd="50.200.196.50" dyno=web.1 connect=0ms service=2ms status=304 bytes=237
2015-12-11T17:45:52.972914+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=campaign-finance.herokuapp.com request_id=1dae858e-7f28-4bb0-bccf-2129cb52fa61 fwd="50.200.196.50" dyno=web.1 connect=0ms service=22ms status=404 bytes=222
2015-12-11T17:46:18.784020+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=7cbf433b-aeab-4ddf-8faf-a5427438b1bb fwd="50.200.196.50" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0
2015-12-11T17:46:39.253981+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=9977f594-119d-48ed-8e54-cd34bc94a3a0 fwd="50.200.196.50" dyno=web.1 connect=1ms service=30004ms status=503 bytes=0
2015-12-11T17:47:01.693103+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=7664822e-6491-4b9f-8b86-6f1c8c95c7cb fwd="50.200.196.50" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0
2015-12-11T17:47:02.366014+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=0ad2be1c-5d94-4afe-b1f9-f0410755f27b fwd="50.200.196.50" dyno=web.1 connect=0ms service=30010ms status=503 bytes=0
2015-12-11T17:47:09.274133+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=bd273163-4e54-4d27-ab4e-39c49c9e9cf6 fwd="50.200.196.50" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0
2015-12-11T17:47:24.391488+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=588b68c9-aa41-4e0d-bcf2-70e818bc6731 fwd="54.84.64.242" dyno=web.1 connect=1ms service=30009ms status=503 bytes=0
2015-12-11T17:47:34.393064+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/data" host=campaign-finance.herokuapp.com request_id=e870727c-ec68-441c-8967-6c76e738f31d fwd="52.91.237.137" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0
```

this is the log... I honestly have no idea how i can decode these messages..

**Comment by RobertAKARobin** [comment]
Your environment variables aren't set properly. At this point, don't worry about it -- just present on localhost.
