### ISSUE TITLE
Errors attempting to npm install figaro

### ISSUE THREAD

**Issue by mpopv** [ga-wdi-exercises/project3#15]
Getting errors when I attempt to install figaro, with a lot of references to 'node-gyp'. Installed node-gyp and that took care of some of them, but still getting several:

```
10 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mattpopovich/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/mattpopovich/.nvm/versions/node/v4.1.2/bin/node" "/Users/mattpopovich/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mattpopovich/.nvm/versions/node/v4.1.2/lib/node_modules/figaro/node_modules/ursa
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:ursa ursa@0.8.5 install: `node-gyp rebuild`
npm WARN install:ursa Exit status 1
/Users/mattpopovich/.nvm/versions/node/v4.1.2/lib
└── (empty)

npm ERR! code 1
```

**Comment by RobertAKARobin** [comment]
I've been trying to find an answer to this but no dice yet, Matt.

**Comment by RobertAKARobin** [comment]
Could you run `npm version` and tell me the output?

**Comment by mpopv** [comment]
```
{ 'project-3-api': '1.0.0',
  npm: '3.3.6',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.1.2',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by RobertAKARobin** [comment]
It looks like you're using an older version of Node: mine is `5.1.0`. Try downloading the newest version, `5.1.1`, from https://nodejs.org/en/
