### ISSUE TITLE
nil:NilClass being saved instead of table data.

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project3#444]
When I post to `https://ccg-link-server.herokuapp.com/events/11/attendances.json`, I get this error
```
2017-03-15T23:44:58.036455+00:00 heroku[router]: at=info method=POST path="/events/11/attendances.json" host=ccg-link-server.herokuapp.com request_id=85941f1d-13a9-49e2-95a4-e2347617db57 fwd="50.200.196.50" dyno=web.1 connect=0ms service=10ms status=500 bytes=257 protocol=https
2017-03-15T23:44:58.029169+00:00 app[web.1]: I, [2017-03-15T23:44:58.029086 #4]  INFO -- : [85941f1d-13a9-49e2-95a4-e2347617db57] Started POST "/events/11/attendances.json" for 50.200.196.50 at 2017-03-15 23:44:58 +0000
2017-03-15T23:44:58.029932+00:00 app[web.1]: I, [2017-03-15T23:44:58.029879 #4]  INFO -- : [85941f1d-13a9-49e2-95a4-e2347617db57] Processing by AttendancesController#create as JSON
2017-03-15T23:44:58.030000+00:00 app[web.1]: I, [2017-03-15T23:44:58.029954 #4]  INFO -- : [85941f1d-13a9-49e2-95a4-e2347617db57]   Parameters: {"attendance"=>{"student_id"=>"1", "event_id"=>"11", "comment"=>"posting from postman"}, "event_id"=>"11"}
2017-03-15T23:44:58.032289+00:00 app[web.1]: D, [2017-03-15T23:44:58.032224 #4] DEBUG -- : [85941f1d-13a9-49e2-95a4-e2347617db57]   Event Load (0.6ms)  SELECT  "events".* FROM "events" WHERE "events"."id" = $1 LIMIT $2  [["id", 11], ["LIMIT", 1]]
2017-03-15T23:44:58.032734+00:00 app[web.1]: ====================1
2017-03-15T23:44:58.033882+00:00 app[web.1]: D, [2017-03-15T23:44:58.033827 #4] DEBUG -- : [85941f1d-13a9-49e2-95a4-e2347617db57]   Student Load (0.5ms)  SELECT  "students".* FROM "students" WHERE "students"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
2017-03-15T23:44:58.034094+00:00 app[web.1]: +=+=+=+=+=+=+=+=+ event:#<Event:0x007f5018833bb8>
2017-03-15T23:44:58.034541+00:00 app[web.1]: +=+=+=+=+=+=+=+=+ student:#<Student id: 1, name: "Wes", email: "wes@mail.ex", linkedin_url: "linkedin.com/wes", github_url: "github.com/wes", bio: "Apprentice web dev", created_at: "2017-03-15 16:45:49", updated_at: "2017-03-15 17:05:46", photo_url: "http://i.imgur.com/XFcOUPx.jpg">
2017-03-15T23:44:58.036176+00:00 app[web.1]: D, [2017-03-15T23:44:58.036123 #4] DEBUG -- : [85941f1d-13a9-49e2-95a4-e2347617db57]   Attendance Load (0.7ms)  SELECT  "attendances".* FROM "attendances" WHERE "attendances"."event_id" = 11 AND "attendances"."student_id" = 1 LIMIT $1  [["LIMIT", 1]]
2017-03-15T23:44:58.036584+00:00 app[web.1]: I, [2017-03-15T23:44:58.036526 #4]  INFO -- : [85941f1d-13a9-49e2-95a4-e2347617db57] Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.8ms)
2017-03-15T23:44:58.037067+00:00 app[web.1]: F, [2017-03-15T23:44:58.037012 #4] FATAL -- : [85941f1d-13a9-49e2-95a4-e2347617db57]   
2017-03-15T23:44:58.037105+00:00 app[web.1]: F, [2017-03-15T23:44:58.037061 #4] FATAL -- : [85941f1d-13a9-49e2-95a4-e2347617db57] NoMethodError (undefined method `save' for nil:NilClass):
2017-03-15T23:44:58.037138+00:00 app[web.1]: F, [2017-03-15T23:44:58.037097 #4] FATAL -- : [85941f1d-13a9-49e2-95a4-e2347617db57]   
2017-03-15T23:44:58.037184+00:00 app[web.1]: F, [2017-03-15T23:44:58.037135 #4] FATAL -- : [85941f1d-13a9-49e2-95a4-e2347617db57] app/controllers/attendances_controller.rb:33:in `block in create'
2017-03-15T23:44:58.037185+00:00 app[web.1]: [85941f1d-13a9-49e2-95a4-e2347617db57] app/controllers/attendances_controller.rb:32:in `create'

```
For some reason, the server won't accept queries to `/events/:id/attendances.json` And I'm not sure why. It worked in the localhost.

**Comment by superbuggy** [comment]
resolved?
