### ISSUE TITLE
Google Login Authentication 

### ISSUE THREAD

**Issue by roshanad** [ga-wdi-exercises/project3#54]
We were able to implement Facebook Login but Google Login is not working.

**Comment by amaseda** [comment]
Are you getting any particular errors? Can you also include relevant code here + repo link? Thx.

**Comment by roshanad** [comment]
https://github.com/codedre/project-3/tree/googleLogin

**Comment by roshanad** [comment]
We are getting throw error when it's trying to save new user that's being pulled from google.

**Comment by roshanad** [comment]
```
        if(err) throw err;
                ^
```

ValidationError: User validation failed
    at MongooseError.ValidationError (/Users/roshan/Project3/project-3/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/Users/roshan/Project3/project-3/node_modules/mongoose/lib/document.js:1280:32)
    at model.Document.set (/Users/roshan/Project3/project-3/node_modules/mongoose/lib/document.js:645:10)
    at model.Object.defineProperty.set [as name](/Users/roshan/Project3/project-3/node_modules/mongoose/lib/document.js:1569:42)
    at Query.<anonymous> (/Users/roshan/Project3/project-3/config/passport.js:127:31)
    at /Users/roshan/Project3/project-3/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /Users/roshan/Project3/project-3/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)

**Comment by jsm13** [comment]
The error is in validating the user so Mongo does not like something that is being given to it. I think it is because what you want to be name, the json from google calls "displayName" so the configuration [here](https://github.com/codedre/project-3/blob/googleLogin/config/passport.js#L127) needs to be changed so that the name is coming from googles "display name". See [example here](https://scotch.io/tutorials/easy-node-authentication-google)

**Comment by roshanad** [comment]
Thank you John!
