### ISSUE TITLE
Slack OAuth

### ISSUE THREAD

**Issue by ascreven** [ga-wdi-exercises/project3#59]
Node is crashing when we're trying to check if OAuth using the Slack API is working. The error that we're getting is 

OAuth2Strategy requires a clientID option

What could be causing this?

**Comment by jshawl** [comment]
you are not supplying the client id. can you share the code where this error is occurring?

**Comment by ascreven** [comment]
The error looks like this: 

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/Users/ascreven/wdi/projects/project-3/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66
  if (!options.clientID) throw new Error('OAuth2Strategy requires a clientID option');
                         ^

Error: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/ascreven/wdi/projects/project-3/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66:32)
    at new Strategy (/Users/ascreven/wdi/projects/project-3/node_modules/passport-slack/lib/passport-slack/strategy.js:54:18)
    at module.exports (/Users/ascreven/wdi/projects/project-3/config/passport.js:38:25)
    at Object.<anonymous> (/Users/ascreven/wdi/projects/project-3/app.js:47:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by RobertAKARobin** [comment]
Do you have a client ID defined anywhere? That would probably be a session variable, or maybe an environment variable.

**Comment by RobertAKARobin** [comment]
I'ma close this for now. Feel free to open a new one!
