### ISSUE TITLE
Local Auth Issue

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#64]
Getting an "unexpected token ." error in my index.js.  Specifically, in `var routes = require('./config/routes');`

That path is correct; entire file is below.  Alia and I worked through my "cannot get /signup" error, and I've created this new one.

``` js
//using express as frame work
var express = require("express");
var app = express();
var bodyParser = require('body-parser');
var candidatesController = require("./controllers/candidatesController");
var usersController = require("./controllers/usersController");
var mongoose     = require('mongoose');
var passport     = require('passport');
var flash        = require('connect-flash');
var hbs          = require("hbs");
var morgan       = require('morgan');
var cookieParser = require('cookie-parser');
var session      = require('express-session');

mongoose.connect('mongodb://localhost/local-authentication-with-passport');

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.use(morgan('dev'));
app.use(cookieParser());


//setting a view handler
app.set("view engine", "hbs");
app.set("views","./views");
app.use(express.static(__dirname + '/public'));

app.use(session({ secret: 'campaign-money' }));
app.use(passport.initialize());
app.use(passport.session());
app.use(flash());

var routes = require('./config/routes');
app.use(routes);

require('./config/passport')(passport);
app.use(function (req, res, next) {
  global.currentUser = req.user;
  res.locals.currentUser = req.user;
  next();
});

// app.get('/signup', usersController.getSignup);

app.get('/', candidatesController.index);
app.get('/candidates', candidatesController.index);

app.get('/candidates/:id', candidatesController.show);

//port listening at local hosting 3000
app.listen(3000, function(){
  console.log("app listening on port 3000");
});
```

**Comment by RobertAKARobin** [comment]
Can you show the whole text of the error, and also link to your code? I'm looking for some line numbers.

VVV Better question

**Comment by jshawl** [comment]
what is the content of `config/routes.js`?

**Comment by ghost** [comment]
My repo is https://github.com/thomhouseholder/campaign-finance/tree/thom-local-user, entire error is 

```
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/thom/wdi/projects/campaign-finance/index.js:33:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by ghost** [comment]
routes.js is 

``` js
var express = require('express');
var passport = require('passport');
var router = express.Router();

var usersController = require('../controllers/usersController');

var candidatesController = require('../controllers/candidatesController');

function authenticatedUser(req, res, next) {
  // If the user is authenticated, then we continue the execution
  if (req.isAuthenticated()) return next();

  // Otherwise the request is always redirected to the home page
  res.redirect('/');
}
// function authenticatedUser()
// router.route( '/', '/signup', '/login', '/logout', '/secret')

router.route('/')
  .get(candidatesController.home);

router.route('/signup')
  .get(usersController.getSignup)
  .post(usersController.postSignup);

router.route('/login')
  .get(usersController.getLogin);
  .post(usersController.postLogin);

router.route("/logout")
  .get(usersController.getLogout);

router.route("/secret")
   .get(authenticatedUser, usersController.secret);

module.exports = router;
```

**Comment by RobertAKARobin** [comment]
I'm trying to run your app, and right off the bat I get `Error: Cannot find module 'mongoose'`, which can be fixed with `npm install --save mongoose`. Then I get another error:

```
ReferenceError: User is not defined
```

Are all the appropriate modules in your package.json?

**Comment by ghost** [comment]
So confused.  I see that happens in the master branch, which I thought was working when I moved into thom-local-auth branch to work on the authorization.

**Comment by ghost** [comment]
I should switch back to master, debug that issue, then create a new branch from there and start over on authentication?
