### ISSUE TITLE
Passport Error

### ISSUE THREAD

**Issue by aoave** [ga-wdi-exercises/project3#69]
Was implementing passport into our app and when I run the nodemon I am getting the error

```[nodemon] starting`node app.js`
module.js:340
    throw err;
    ^

Error: Cannot find module 'passport'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Ao/wdi/projects/SwoleMate/app.js:3:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
[nodemon] app crashed - waiting for file changes before starting...```

I have it required where I need to have it but still getting this error

**Comment by jshawl** [comment]
try `npm install --save passport`
