### ISSUE TITLE
Flash messages breaking local auth

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#97]
i'm able to make the local login and signup processes work when flash messages are commented out.  when i include them in res.render( ), the process breaks 

my repo is https://github.com/thomhouseholder/campaign-finance/commits/thom-second-try-local-user

my usersController signup route code is 

```
// GET /signup
function getSignup(request, response) {
  response.render("signup.hbs", { message: request.flash('signupMessage') });
}
```

and my passport snippet is 

```
passport.use('local-signup', new LocalStrategy({
     usernameField : 'email',
     passwordField : 'password',
     passReqToCallback : true
     }, function(req, email, password, callback) {
     // Find a user with this e-mail
     User.findOne({ 'local.email' :  email }, function(err, user) {
       if (err) return callback(err);

       // If there already is a user with this email
       if (user) {
     return callback(null, false, req.flash('signupMessage', 'This email is already used.'));
       } else {
       // There is no email registered with this emai
     // Create a new user
     var newUser            = new User();
     newUser.local.email    = email;
     newUser.local.password = newUser.encrypt(password);
```

my error message is 

```
Error: req.flash() requires sessions
    at Error (native)
    at IncomingMessage._flash [as flash] (/Users/thom/wdi/projects/campaign-finance/node_modules/connect-flash/lib/flash.js:60:41)
    at Object.getSignup [as handle] (/Users/thom/wdi/projects/campaign-finance/controllers/usersController.js:5:52)
    at next_layer (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/route.js:107:5)
    at /Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:195:24
    at Function.proto.process_params (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:251:12)
    at next (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:189:19)
    at next (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:166:38)
    at Function.proto.handle (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:234:5)
    at Layer.router (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:23:12)
    at trim_prefix (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:226:17)
    at /Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:198:9
    at Function.proto.process_params (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:251:12)
    at next (/Users/thom/wdi/projects/campaign-finance/node_modules/express/lib/router/index.js:189:19)
```

**Comment by jshawl** [comment]
`Error: req.flash() requires sessions` - do you have express-session anywhere in your code? like https://github.com/ga-dc/express-passport-local-authentication/blob/01c61bbdf8d3933145378750aac98ad35eeb8523/app.js#L10

**Comment by ghost** [comment]
I do.  it's in my index.js

`var session = require('express-session');`

and just ran npm install --save express-session again but no change of results

**Comment by jshawl** [comment]
are you using the session? https://github.com/ga-dc/express-passport-local-authentication/blob/01c61bbdf8d3933145378750aac98ad35eeb8523/app.js#L10

**Comment by ghost** [comment]
app.use(session({secret: 'wazzup'}));

I am now.  Thanks for the hints.  

Oversimplifying to say a smart check is to ensure everything that's required has a corresponding .use or .set ?  Otherwise they're just sitting on the shelf, right?

**Comment by jshawl** [comment]
I believe so. I knew it was session related because of the error message: `Error: req.flash() requires sessions`
