### ISSUE TITLE
Broken Authorization

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-wdi-exercises/project3#99]
I'm getting a error when I use my sign-in & signup button to submit.

```
TypeError: next is not a function at attempt (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/passport/lib/passport/middleware/authenticate.js:237:32) at Passport.authenticate (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/passport/lib/passport/middleware/authenticate.js:244:7) at Object.postLogin [as handle] (/Users/korycampbell/wdi/projects/project3/hackerbnb/controllers/users.js:30:10) at next_layer (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/route.js:103:13) at next_layer (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/route.js:81:14) at Route.dispatch (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/route.js:107:5) at /Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:195:24 at Function.proto.process_params (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:251:12) at next (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:189:19) at next (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:166:38) at next (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:166:38) at Function.proto.handle (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:234:5) at Layer.router (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:23:12) at trim_prefix (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:226:17) at /Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:198:9 at Function.proto.process_params (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:251:12)

```

**Comment by KoryJCampbell** [comment]
```
TypeError: next is not a function at attempt (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/passport/lib/passport/middleware/authenticate.js:237:32) at Passport.authenticate (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/passport/lib/passport/middleware/authenticate.js:244:7) at Object.postLogin [as handle] (/Users/korycampbell/wdi/projects/project3/hackerbnb/controllers/users.js:30:10) at next_layer (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/route.js:103:13) at next_layer (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/route.js:81:14) at Route.dispatch (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/route.js:107:5) at /Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:195:24 at Function.proto.process_params (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:251:12) at next (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:189:19) at next (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:166:38) at next (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:166:38) at Function.proto.handle (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:234:5) at Layer.router (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:23:12) at trim_prefix (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:226:17) at /Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:198:9 at Function.proto.process_params (/Users/korycampbell/wdi/projects/project3/hackerbnb/node_modules/express/lib/router/index.js:251:12)
```

**Comment by jshawl** [comment]
can you sahre your code for this file: controllers/users.js:30

**Comment by KoryJCampbell** [comment]
```
  return loginProperty(request, response);
}

// logout
function getLogout(request, response) {
  request.logout();
  response.redirect('/');
}

// secret
function secret(request, response){
  response.render("secret.hbs");
}

module.exports = {
  getLogin: getLogin,
  postLogin: postLogin ,
  getSignup: getSignup,
  postSignup: postSignup,
  getLogout: getLogout,
  secret: secret
};

```

**Comment by jshawl** [comment]
can you link to your repo or share the whole file? unable to tell what the issue is so far

**Comment by KoryJCampbell** [comment]
https://github.com/KoryJCampbell/wegotthis/tree/Kory

**Comment by KoryJCampbell** [comment]
branch: Kory

**Comment by jshawl** [comment]
can you signup  successfully? is it only login thats an issue?

**Comment by KoryJCampbell** [comment]
It throws the same error for login & signup

**Comment by jshawl** [comment]
ok pulling down loclly to test

**Comment by jshawl** [comment]
uncomment this line https://github.com/KoryJCampbell/wegotthis/blob/96613dfdb07ff2b89fee9d4f933d7f4df1791a73/app.js#L34

**Comment by KoryJCampbell** [comment]
got it thanks
